"""empty message

Revision ID: 22111ef71552
Revises: 62e2b12a4391
Create Date: 2017-02-14 16:23:26.243068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22111ef71552'
down_revision = '62e2b12a4391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
