"""empty message

Revision ID: 47a473ff591b
Revises: 22111ef71552
Create Date: 2017-02-15 10:17:28.890949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a473ff591b'
down_revision = '22111ef71552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('books', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('books', 'book_description')
    op.drop_column('books', 'book_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('book_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('books', 'title')
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
