"""empty message

Revision ID: 997f195f9f6a
Revises: e3ffaa2c9d55
Create Date: 2017-02-15 23:04:54.696989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997f195f9f6a'
down_revision = 'e3ffaa2c9d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'quantity')
    # ### end Alembic commands ###
