"""empty message

Revision ID: e259b201c080
Revises: 47a473ff591b
Create Date: 2017-02-15 10:21:18.754675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e259b201c080'
down_revision = '47a473ff591b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_created_by_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_created_by_fkey', 'books', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
