"""empty message

Revision ID: e3ffaa2c9d55
Revises: b09368b5d6f6
Create Date: 2017-02-15 21:22:55.011595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ffaa2c9d55'
down_revision = 'b09368b5d6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('borrow_date', sa.DateTime(), nullable=True))
    op.add_column('user_books', sa.Column('return_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'return_date')
    op.drop_column('user_books', 'borrow_date')
    # ### end Alembic commands ###
